import 'server-only'
import type { AppConfig } from '@/lib/config/schema'
import { Octokit } from '@octokit/rest'
import { prisma } from '@/lib/db/prisma'

function generatePrismaSchema(config: AppConfig): string {
  const models = config.resources.map(resource => {
    const fields = resource.fields.map(f => {
      const typeMap: Record<string, string> = {
        text: 'String', email: 'String', url: 'String', richtext: 'String',
        number: 'Float', boolean: 'Boolean', date: 'DateTime', datetime: 'DateTime',
        select: 'String', multiselect: 'String[]', json: 'Json', file: 'String',
        relation: 'String',
      }
      const prismaType = typeMap[f.type] ?? 'String'
      const optional = !f.required ? '?' : ''
      return `  ${f.name} ${prismaType}${optional}`
    })

    return `model ${resource.name.charAt(0).toUpperCase() + resource.name.slice(1)} {
  id        String   @id @default(uuid())
${fields.join('\n')}
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`
  })

  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models.join('\n\n')}`
}

function generatePageFile(config: AppConfig, pagePath: string): string {
  const page = config.pages.find(p => p.path === pagePath)
  const components = page?.components.map(c => `  // ${c.type}: ${c.id}`).join('\n') ?? ''

  return `// Auto-generated page: ${pagePath}
export default function GeneratedPage() {
  return (
    <div>
      <h1>${page?.title ?? pagePath}</h1>
      {/* Components:
${components}
      */}
    </div>
  )
}
`
}

export interface GeneratedFile {
  path:    string
  content: string
}

export function generateProjectFiles(config: AppConfig): GeneratedFile[] {
  const files: GeneratedFile[] = []

  // package.json
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name:    config.name.toLowerCase().replace(/\s+/g, '-'),
      version: '0.1.0',
      private: true,
      scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
      dependencies: {
        next: '^16.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        '@prisma/client': '^6.0.0',
      },
      devDependencies: {
        typescript: '^5.0.0',
        '@types/node': '^20.0.0',
        '@types/react': '^19.0.0',
        prisma: '^6.0.0',
      },
    }, null, 2),
  })

  // Embedded app config
  files.push({
    path: 'src/lib/appConfig.ts',
    content: `// Auto-generated config\nexport const appConfig = ${JSON.stringify(config, null, 2)} as const\n`,
  })

  // Prisma schema
  files.push({
    path: 'prisma/schema.prisma',
    content: generatePrismaSchema(config),
  })

  // Pages
  for (const page of config.pages) {
    const fileName = page.path === '/' ? 'index' : page.path.replace(/^\//, '').replace(/\//g, '-')
    files.push({
      path: `src/app/${fileName}/page.tsx`,
      content: generatePageFile(config, page.path),
    })
  }

  // README
  files.push({
    path: 'README.md',
    content: `# ${config.name}\n\n${config.description ?? ''}\n\nGenerated by AI App Generator.\n`,
  })

  return files
}

export async function exportToGitHub(
  jobId:      string,
  appId:      string,
  config:     AppConfig,
  githubToken: string,
  repoName:   string,
  orgOrUser:  string
): Promise<string> {
  await prisma.exportJob.update({ where: { id: jobId }, data: { status: 'GENERATING' } })

  const files = generateProjectFiles(config)
  const octokit = new Octokit({ auth: githubToken })

  // Create repo
  const { data: repo } = await octokit.repos.createForAuthenticatedUser({
    name:    repoName,
    private: false,
    description: config.description ?? `Generated app: ${config.name}`,
    auto_init: true,
  })

  // Push files
  for (const file of files) {
    try {
      await octokit.repos.createOrUpdateFileContents({
        owner:   repo.owner.login,
        repo:    repo.name,
        path:    file.path,
        message: `feat: add ${file.path}`,
        content: Buffer.from(file.content).toString('base64'),
      })
    } catch (err) {
      console.error(`Failed to push ${file.path}:`, err)
    }
  }

  const repoUrl = repo.html_url

  await prisma.exportJob.update({
    where: { id: jobId },
    data:  { status: 'COMPLETED', repoUrl, completedAt: new Date() },
  })

  return repoUrl
}

export async function generateExportZip(config: AppConfig): Promise<Buffer> {
  // Simple JSON export as fallback (no native zip in Node without archiver)
  const files = generateProjectFiles(config)
  const manifest = JSON.stringify({ files: files.map(f => ({ path: f.path, size: f.content.length })) }, null, 2)
  const fullContent = files.map(f => `\n${'='.repeat(60)}\n// ${f.path}\n${'='.repeat(60)}\n${f.content}`).join('\n')
  return Buffer.from(manifest + '\n\n' + fullContent, 'utf-8')
}
